Repository magento/magento-functional-tests-migration, pull requests merged in 2020-04, with the labels that each got.

#724 Add test for admin user role create functionality
  app/code/Magento/User/Test/Mftf/ActionGroup/AssertAdminRoleInGridActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AssertAdminRoleNotInGridActionGroup.xml
  app/code/Magento/User/Test/Mftf/Section/AdminRoleGridSection/AdminRoleGridSection.xml
  app/code/Magento/User/Test/Mftf/Test/AdminCreateUserRoleEntityTest.xml
  dev/tests/functional/tests/app/Magento/User/Test/TestCase/CreateAdminUserRoleEntityTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#717 Issue 709/create admin user entity test
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminCreateUserWithRoleAndIsInactiveActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminDeleteUserActionGroup.xml
  app/code/Magento/User/Test/Mftf/Data/UserData.xml
  app/code/Magento/User/Test/Mftf/Data/UserRoleData.xml
  app/code/Magento/User/Test/Mftf/Test/AdminCreateActiveUserEntityTest.xml
  app/code/Magento/User/Test/Mftf/Test/AdminCreateInactiveUserEntityTest.xml
  app/code/Magento/User/Test/Mftf/Test/AdminLockAdminUserEntityTest.xml
Labels: Partner: Divante, Progress: review, partners-contribution

#710 #580 Convert DeleteSystemCustomerGroupTest to MFTF
  app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminOpenCustomerGroupEditPageFromGridActionGroup.xml
  app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminOpenCustomerGroupsGridPageActionGroup.xml
  app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertDeleteCustomerGroupButtonMissingActionGroup.xml
  app/code/Magento/Customer/Test/Mftf/Section/AdminEditCustomerGroupSection.xml
  app/code/Magento/Customer/Test/Mftf/Test/AdminCustomersDeleteSystemCustomerGroupTest.xml
  dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/DeleteSystemCustomerGroupTest.xml
Labels: Partner: Atwix, Progress: review, partners-contribution

#706 622 Convert CreateCmsBlockEntityTest to MFTF
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminCategoriesExpandAllActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminCategoriesOpenCategoryActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminCategoriesOpenContentSectionActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminCategoriesSetDisplayModeActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminCategoriesSetStaticBlockActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminOpenCategoriesPageActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminSaveCategoryActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/ActionGroup/AdminSetCMSBlockDisabledActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/ActionGroup/AdminSetCMSBlockEnabledActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/ActionGroup/AssertStorefrontNoTextOnCategoryPageActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/ActionGroup/AssertStorefrontTextOnCategoryPageActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/Section/CmsNewBlockBlockBasicFieldsSection/BlockNewPageBasicFieldsSection.xml
  app/code/Magento/Cms/Test/Mftf/Test/AdminCreateDisabledCmsBlockEntityAndAssignToCategoryTest.xml
  app/code/Magento/Cms/Test/Mftf/Test/AdminCreateEnabledCmsBlockEntityAndAssignToCategoryTest.xml
  dev/tests/functional/tests/app/Magento/Cms/Test/TestCase/CreateCmsBlockEntityTest.xml
Labels: Award: complex, Partner: Atwix, Progress: delivery, partners-contribution
