Repository magento/magento-functional-tests-migration, pull requests merged in 2020-05, with the labels that each got.

#776 Issue #449 Convert ProductsInCartReportEntityTest to MFTF
  app/code/Magento/Backend/Test/Mftf/ActionGroup/AdminOpenReportProductsInCartsPageActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminAssertProductPresentOnProductsInCartsReportActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/Page/AdminReportProductsInCartsPage.xml
  app/code/Magento/Reports/Test/Mftf/Section/AdminReportProductsInCartsGridSection.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminReportsProductsInCartsWithOneCartTest.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminReportsProductsInCartsWithTwoCartsTest.xml
Labels: Partner: Atwix, Progress: review, partners-contribution

#775 Search terms report entity test
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminSearchTermsReportFilterQueryActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminSearchTermsReportGridClickRowActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/Data/AdminMenuData.xml
  app/code/Magento/Reports/Test/Mftf/Data/SearchTermsData.xml
  app/code/Magento/Reports/Test/Mftf/Section/AdminSearchTermsReportFilterSection.xml
  app/code/Magento/Reports/Test/Mftf/Section/AdminSearchTermsReportFormSection.xml
  app/code/Magento/Reports/Test/Mftf/Section/AdminSearchTermsReportMainSection.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminReportsSearchTermsWithMultipleHitsTest.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminReportsSearchTermsWithMultipleResultsTest.xml
  dev/tests/functional/tests/app/Magento/Reports/Test/TestCase/SearchTermsReportEntityTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#774 Issue #321 Convert CheckShowSwatchesInProductListOptionImpactTest to …
  app/code/Magento/Swatches/Test/Mftf/ActionGroup/AdminCreateConfigurableProductWithOneAttributeActionGroup.xml
  app/code/Magento/Swatches/Test/Mftf/ActionGroup/StorefrontAssertSwatchAttributeOptionsOnProductListIsNotVisibleActionGroup.xml
  app/code/Magento/Swatches/Test/Mftf/ActionGroup/StorefrontAssertSwatchAttributeOptionsOnProductListIsVisibleActionGroup.xml
  app/code/Magento/Swatches/Test/Mftf/Data/SwatchAttributeData.xml
  app/code/Magento/Swatches/Test/Mftf/Data/SwatchConfigData.xml
  app/code/Magento/Swatches/Test/Mftf/Section/StorefrontProductInfoMainSection.xml
  app/code/Magento/Swatches/Test/Mftf/Test/StorefrontDisableSwatchesOnCategoryPageTest.xml
  app/code/Magento/Swatches/Test/Mftf/Test/StorefrontEnableSwatchesOnCategoryPageTest.xml
  dev/tests/functional/tests/app/Magento/Swatches/Test/TestCase/CheckShowSwatchesInProductListOptionImpactTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#773 Issue #463 Convert CheckoutWithPersistentShoppingCartTest to MFTF
  app/code/Magento/Persistent/Test/Mftf/ActionGroup/StorefrontAssertFirstStepOnCheckoutIsAvailableActionGroup.xml
  app/code/Magento/Persistent/Test/Mftf/Test/StorefrontCheckoutWithPersistentShoppingCartTest.xml
  dev/tests/functional/tests/app/Magento/Persistent/Test/TestCase/CheckoutWithPersistentShoppingCartTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#772 Edit Currency Custom Website
  app/code/Magento/Catalog/Test/Mftf/Section/StorefrontProductPageSection.xml
  app/code/Magento/CurrencySymbol/Test/Mftf/ActionGroup/AssertStorefrontCurrencySymbolOnProductPageActionGroup.xml
  app/code/Magento/CurrencySymbol/Test/Mftf/Test/AdminEditCurrencyCustomWebsiteTest.xml
  dev/tests/functional/tests/app/Magento/CurrencySymbol/Test/TestCase/EditCurrencyCustomWebsiteTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#771 Convert DeleteSynonymGroupEntityTest to MFTF
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminClickNewSynonymGroupButtonActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminClickSaveButtonOnSynonymGroupFormActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminDeleteFirstSynonymGroupEntityFromTheGridActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminFillNewSynonymGroupFormRequiredFieldsActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminOpenSearchSynonymsGridActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminSearchSynonymGroupBySynonymsActionGroup.xml
  app/code/Magento/Search/Test/Mftf/Data/SynonymGroupData.xml
  app/code/Magento/Search/Test/Mftf/Page/AdminSearchSynonymsPage.xml
  app/code/Magento/Search/Test/Mftf/Section/AdminNewSynonymsGroupFormSection.xml
  app/code/Magento/Search/Test/Mftf/Section/AdminSearchSynonymsGridSection.xml
  app/code/Magento/Search/Test/Mftf/Test/AdminDeleteSynonymGroupEntityTest.xml
  dev/tests/functional/tests/app/Magento/Search/Test/TestCase/DeleteSynonymGroupEntityTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#754 Issue 271 create bundle product entity test
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminAddBundleOptionTwoProductsWithPriceTypeAndValueActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminAddProductCustomOptionSelectWithOneValueActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminCreateBundleProductActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminCreateBundleProductWithDescriptionAndWeightActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminCreateBundleProductWithTaxClassActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AdminCreateBundleProductWithTaxStockVisibilityAndWeightActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontCategoryPageWithPriceRangeActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontCategoryPageWithRegularPriceActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontProductPageWithPriceAndDescriptionActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontProductPageWithPriceRangeActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontProductPageWithRegularPriceActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductInStorefrontProductPageWithStockActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertBundleProductItemsInStorefrontProductPageActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertProductFormInAdminWithBundleOptionActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/AssertProductSearchableBySkuActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/ActionGroup/StorefrontAddBundleProductWithCustomOptionsToCartActionGroup.xml
  app/code/Magento/Bundle/Test/Mftf/Data/BundleCustomOptionsData.xml
  app/code/Magento/Bundle/Test/Mftf/Data/BundlePriceRangeData.xml
  app/code/Magento/Bundle/Test/Mftf/Data/ProductData.xml
  app/code/Magento/Bundle/Test/Mftf/Section/AdminProductFormBundleSection.xml
  app/code/Magento/Bundle/Test/Mftf/Section/StorefrontBundledSection.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductAndAssertPriceViewAndType.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductEntityTestAndCheckSave.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductOutOfStock.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductTwoOptionsFixedAndPercentPrices.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductWithCustOptionsAndSpecPrice.xml
  app/code/Magento/Bundle/Test/Mftf/Test/AdminCreateBundleProductWithItems.xml
  dev/tests/functional/tests/app/Magento/Bundle/Test/TestCase/CreateBundleProductEntityTest.xml
Labels: Progress: approved

#745 Convert CreateCmsPageRewriteEntityTest to MFTF
  app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminAddUrlRewriteForCmsPageActionGroup.xml
  app/code/Magento/UrlRewrite/Test/Mftf/Test/AdminCreateCmsPageRewriteEntityTest.xml
  dev/tests/functional/tests/app/Magento/Cms/Test/TestCase/CreateCmsPageRewriteEntityTest.xml
Labels: Award: special achievement, Partner: Atwix, Progress: approved, Waiting Response, partners-contribution

#727 Issue 306 update password user entity pci requirements
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminProvideNewUserPasswordActionGroup.xml
  app/code/Magento/User/Test/Mftf/Test/AdminUpdatePasswordUserEntityPciRequirementsTest.xml
  dev/tests/functional/tests/app/Magento/User/Test/TestCase/UpdatePasswordUserEntityPciRequirementsTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#726 Add test to check admin user success login after changing user permis…
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminOpenRoleEditPageActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminUpdateRoleResourceAccessActionGroup.xml
  app/code/Magento/User/Test/Mftf/Test/AdminUserLoginAfterChangingPermissionsTest.xml
  dev/tests/functional/tests/app/Magento/User/Test/TestCase/UserLoginAfterChangingPermissionsTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#722 Add test for admin user role delete functionality
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminRoleGridFilterByNameActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminRoleGridOpenFirstRowActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminRoleOpenGridActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AdminUpdateUserRoleUsingCustomAdminPasswordActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AssertAdminUserRoleInGridActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AssertAdminUserRoleNotInGridActionGroup.xml
  app/code/Magento/User/Test/Mftf/ActionGroup/AssertImpossibleDeleteYourOwnRoleActionGroup.xml
  app/code/Magento/User/Test/Mftf/Test/AdminDeleteUserRoleEntityTest.xml
  dev/tests/functional/tests/app/Magento/User/Test/TestCase/DeleteUserRoleEntityTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#736 Converting CreateDuplicateUrlCmsPageEntityTest to MFTF #616
  app/code/Magento/Cms/Test/Mftf/ActionGroup/CreateNewPageWithDuplicateUrlActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/ActionGroup/VerifySaveCMSPageFailureOnDuplicationUrlActionGroup.xml
  app/code/Magento/Cms/Test/Mftf/Test/CreateDuplicateUrlCmsPageEntityTest.xml
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#738 293: Convert AddProductToWishlistEntityTest to MFTF
  app/code/Magento/Catalog/Test/Mftf/Data/CatalogSpecialPriceData.xml
  app/code/Magento/Wishlist/Test/Mftf/ActionGroup/AdminAssertProductIsPresentInCustomerBackendWishlistActionGroup.xml
  app/code/Magento/Wishlist/Test/Mftf/ActionGroup/AdminDeleteProductFromWishlistOnBackendActionGroup.xml
  app/code/Magento/Wishlist/Test/Mftf/Section/StorefrontCustomerWishlistProductSection.xml
  app/code/Magento/Wishlist/Test/Mftf/Section/WishlistGeneralSection.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/DeleteConfigurableProductFromCustomerWishlistOnBackendTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/DeleteSimpleProductFromCustomerWishlistOnBackendTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddBundleProductToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddConfigurableProductToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddConfigurableProductWithSpecialPriceToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddConfigurableProductWithoutConfigureToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddDownloadableProductToWishListTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddDownloadableProductWithSpecialPriceToWishListTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddGroupedProductToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddGroupedProductWithSpecialPriceToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddSimpleProductWithSpecialPriceToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddVirtualProductToWishlistTest.xml
  app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontAddVirtualProductWithSpecialPriceToWishlistTest.xml
  dev/tests/functional/tests/app/Magento/Wishlist/Test/TestCase/AddProductToWishlistEntityTest.xml
  dev/tests/functional/tests/app/Magento/Wishlist/Test/TestCase/DeleteProductFromCustomerWishlistOnBackendTest.xml
Labels: Progress: changes requested

#752 Convert CreateProductRatingEntityTest to MFTF #434
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminDeleteProductRatingActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminFillInActiveRatingActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminFillInInactiveRatingActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminOpenNewRatingFormActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminSaveProductRatingActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/AdminSearchForRatingCodeInGridActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/StorefrontAddProductReviewActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/StorefrontAddProductReviewAsCustomerActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/StorefrontAddProductReviewWithRatingActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/StorefrontAddProductReviewWithRatingAsCustomerActionGroup.xml
  app/code/Magento/Review/Test/Mftf/ActionGroup/StorefrontOpenProductPageReviewsActionGroup.xml
  app/code/Magento/Review/Test/Mftf/Data/ProductRatingData.xml
  app/code/Magento/Review/Test/Mftf/Data/ProductReviewData.xml
  app/code/Magento/Review/Test/Mftf/MetaData/product_rating-meta.xml
  app/code/Magento/Review/Test/Mftf/Page/AdminRatingEditPage.xml
  app/code/Magento/Review/Test/Mftf/Page/AdminRatingGridPage.xml
  app/code/Magento/Review/Test/Mftf/Page/AdminRatingNewPage.xml
  app/code/Magento/Review/Test/Mftf/Section/AdminEditRatingSection.xml
  app/code/Magento/Review/Test/Mftf/Section/AdminNewRatingSection.xml
  app/code/Magento/Review/Test/Mftf/Section/AdminRatingGridSection.xml
  app/code/Magento/Review/Test/Mftf/Test/AdminCreateActiveProductRatingTest.xml
  app/code/Magento/Review/Test/Mftf/Test/AdminCreateInactiveProductRatingTest.xml
  app/code/Magento/Review/Test/Mftf/Test/AdminDeleteProductRatingTest.xml
  app/code/Magento/Review/Test/Mftf/Test/StorefrontCreateProductReviewWithRatingAsCustomerTest.xml
  app/code/Magento/Review/Test/Mftf/Test/StorefrontCreateProductReviewWithRatingTest.xml
Labels: Progress: review

#758 391 convert merge synonym group entity test mftf
  app/code/Magento/Cms/Test/Mftf/ActionGroup/DeletePageByUrlKeyActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminCreateSynonymActionGroup.xml
  app/code/Magento/Search/Test/Mftf/ActionGroup/AdminCreateSynonymWithMergeActionGroup.xml
  app/code/Magento/Search/Test/Mftf/Page/AdminSynonymGroupEntityEditPage.xml
  app/code/Magento/Search/Test/Mftf/Section/AdminSynonymGroupEntitySection.xml
  app/code/Magento/Search/Test/Mftf/Test/AdminMergeSynonymGroupEntityTest.xml
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#763 Convert Activate Integration Entity Test
  app/code/Magento/Integration/Test/Mftf/ActionGroup/AdminIntegrationSaveAndActivateClickActionGroup.xml
  app/code/Magento/Integration/Test/Mftf/ActionGroup/AssertAdminIntegrationResourcesPopupActionGroup.xml
  app/code/Magento/Integration/Test/Mftf/ActionGroup/AssertAdminIntegrationTokensPopupActionGroup.xml
  app/code/Magento/Integration/Test/Mftf/Data/IntegrationData.xml
  app/code/Magento/Integration/Test/Mftf/Section/AdminNewIntegrationSection.xml
  app/code/Magento/Integration/Test/Mftf/Test/AdminActivateIntegrationEntityTest.xml
  dev/tests/functional/tests/app/Magento/Integration/Test/TestCase/ActivateIntegrationEntityTest.xml
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#767 Low Stock Report
  app/code/Magento/Catalog/Test/Mftf/Data/ProductData.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminReportsFindLowStockProductActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminReportsLowStockResetFilterActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AssertAdminLowStockProductInGridActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/Section/LowStockReportMainSection.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminReportsLowStockProductsReportEntityTest.xml
  dev/tests/functional/tests/app/Magento/Reports/Test/TestCase/LowStockProductsReportEntityTest.xml
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#768 Convert ReorderOrderEntityTest to MFTF #409
  app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminChangeBillingAddressOnCreateOrderPageActionGroup.xml
  app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminOpenReorderPageActionGroup.xml
  app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminCheckOrderStatusAndGrandTotalInOrdersGridActionGroup.xml
  app/code/Magento/Sales/Test/Mftf/Test/AdminReorderOrderEntityTest.xml
  dev/tests/acceptance/tests/functional/Magento/_generated/default/AdminReorderOrderEntityTestCest.php
  dev/tests/functional/tests/app/Magento/Sales/Test/TestCase/ReorderOrderEntityTest.xml
  tests/_output/.gitignore
Labels: Partner: Atwix, Progress: review, partners-contribution

#769 Convert ShoppingCartWithFreeShippingTest to MFTF #394
  app/code/Magento/Checkout/Test/Mftf/ActionGroup/AssertStorefrontShippingMethodNotPresentInCartActionGroup.xml
  app/code/Magento/SalesRule/Test/Mftf/ActionGroup/AdminCartPriceRuleGridOpenActionGroup.xml
  app/code/Magento/SalesRule/Test/Mftf/ActionGroup/AdminCreateCartPriceRuleWithOneConditionActionGroup.xml
  app/code/Magento/SalesRule/Test/Mftf/ActionGroup/AdminOpenExistingCartPriceRuleByNameActionGroup.xml
  app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontShoppingCartWithFreeShippingTest.xml
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#778 Issue 518 Convert ProductsCountInLayeredNavigationTest to MFTF
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminEnableDisableProductsViaBulkActionInProductGridActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminSelectDeselectAllProductsInTheGridActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/AssertStorefrontCategoryIsEmptyActionGroup.xml
  app/code/Magento/Catalog/Test/Mftf/ActionGroup/StorefrontOpenCategoryPageByURLActionGroup.xml
  app/code/Magento/LayeredNavigation/Test/Mftf/ActionGroup/AssertStorefrontAttributesCountForShoppingOptionInLayeredNavigationActionGroup.xml
  app/code/Magento/LayeredNavigation/Test/Mftf/ActionGroup/AssertStorefrontProductsCountForAttributeInLayeredNavigationActionGroup.xml
  app/code/Magento/LayeredNavigation/Test/Mftf/Section/LayeredNavigationSection/StorefrontLayeredNavigationSection.xml
  app/code/Magento/LayeredNavigation/Test/Mftf/Test/StorefrontProductsCountInLayeredNavigationWithDisabledByMassactionProductsTest.xml
  app/code/Magento/LayeredNavigation/Test/Mftf/Test/StorefrontProductsCountInLayeredNavigationWithDisabledFromProductEditPageProductsTest.xml
  dev/tests/functional/tests/app/Magento/LayeredNavigation/Test/TestCase/ProductsCountInLayeredNavigationTest.xml
Labels: Award: complex, Partner: Atwix, Progress: changes requested, partners-contribution

#782 Issue 444 bestseller products report entity test
  app/code/Magento/Analytics/Test/Mftf/Data/AdminMenuData.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminGenerateBestsellersReportActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminRefreshStatisticsForReportActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/ActionGroup/AdminSeeProductInBestsellersReportActionGroup.xml
  app/code/Magento/Reports/Test/Mftf/Section/BestsellersReportFilterSection.xml
  app/code/Magento/Reports/Test/Mftf/Section/BestsellersReportGridSection.xml
  app/code/Magento/Reports/Test/Mftf/Section/RefreshStatisticsGridSection.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminBestsellerProductsReportForSimpleProductAnnualEntityTest.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminBestsellerProductsReportForSimpleProductDailyEntityTest.xml
  app/code/Magento/Reports/Test/Mftf/Test/AdminBestsellerProductsReportForVirtualProductMonthlyEntityTest.xml
  dev/tests/functional/tests/app/Magento/Reports/Test/TestCase/BestsellerProductsReportEntityTest.xml
Labels: Partner: Atwix, Progress: review, partners-contribution
